# general settings
name: lite_dvd_train
model_name: LiteDVDNet
module: 'litedvdnet'
model_params:
  num_input_frames: 5
  channels: [32, 64, 128]
  inference_mode: Basic
  interm_ch: 30
  simple_cv: false
manual_seed: 10
use_cuda: true
batch_size: 64
epochs: 80
resume_training: false
resume_dir: ''
milestones: [3, 4, 25, 70]
learning_rates: [0.01, 0.001, 0.0001, 0.000001]
orthog_epochs: 60
lr: 0.001
save_every: 10
save_ckpt_every_epochs: 1
noise_ival: [5, 55]
val_noiseL: 25.0
patch_size: 96
temp_patch_size: 5
max_number_patches: 32000
trainset_dir: './datasets/davis2017/videos/480p'
valset_dir: './datasets/Set8/validation'



